name: pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  run_workflow:
    runs-on: ubuntu-latest

    permissions:
        contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run pipeline
        working-directory: src
        run: |
          python main.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
