name: test_scrapy_with_mongodb

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  run_workflow:
    runs-on: ubuntu-latest

    permissions:
        contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run scrapy
        working-directory: src/bookscraper/bookscraper/spiders
        run: |
          echo scrapy crawl -s MONGODB_URI="mongodb+srv://${{ secrets.MONGO_DB_USERNAME }}:${{ secrets.MONGO_DB_PASSWORD }}@cluster0.2ivt0kx.mongodb.net/?retryWrites=true&w=majority" -s MONGODB_DATABASE="scrapy" products
