name: pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 29 1 *'

jobs:
  run_workflow:
    runs-on: ubuntu-latest

    permissions:
        contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run spider
        working-directory: src/scrapers
        run: |
          python async_scraper.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
